[workspace]
resolver = "3"
members = [
    "crates/bota-bot",
    "crates/bota-client",
    "crates/bota-proto",
    "crates/bota-server",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
bota-proto = { path = "crates/bota-proto" }

[workspace.lints.clippy]
float_arithmetic = "deny"
