[package]
name = "bota-server"
version.workspace = true
edition.workspace = true

[dependencies]
bota-proto = { workspace = true }
rand_chacha = "0.10"
clap = { version = "4", features = ["derive"] }
rustc-hash = { version = "2.1.3", default-features = false, features = ["std"] }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "dummy"
path = "benches/dummy/main.rs"
harness = false

[lints]
workspace = true
